
  export const WorkoutsArray =
  [
  {'id':11,'woname':'tensandtwos','displayname':'tensandtwos','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':12,'woname':'agilitycircles','displayname':'agilitycircles','wodirection':'right', 'duration':30,'targetarea':'full'},
  {'id':13,'woname':'alternatingsupermans','displayname':'alternatingsupermans','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':14.1,'woname':'balancereaches','displayname':'balancereaches-right','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':14.2,'woname':'balancereaches','displayname':'balancereaches-left','wodirection':'left', 'duration':30,'targetarea':'lower'},
  {'id':15,'woname':'bicycles','displayname':'bicycles','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':16,'woname':'burpees','displayname':'burpees','wodirection':'right', 'duration':30,'targetarea':'full'},
  {'id':17,'woname':'crossbodyv','displayname':'crossbody-v','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':18,'woname':'crunches','displayname':'crunches','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':19,'woname':'curtsylunges','displayname':'curtsylunges','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':20,'woname':'diagonallunges','displayname':'diagonallunges','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':21,'woname':'divebomberpushup','displayname':'divebomberpushup','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':22,'woname':'doublecrunches','displayname':'doublecrunches','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':23,'woname':'hellodollies','displayname':'hellodollies','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':24,'woname':'hightailpushups','displayname':'hightailpushups','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':25,'woname':'jumplunges','displayname':'jumplunges','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':26,'woname':'jumpsquats','displayname':'jumpsquats','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':27,'woname':'jumpingjacks','displayname':'jumpingjacks','wodirection':'right', 'duration':30,'targetarea':'full'},
  {'id':28,'woname':'laterallunges','displayname':'laterallunges','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':29,'woname':'lunges','displayname':'lunges','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':30,'woname':'mountainclimbers','displayname':'mountainclimbers','wodirection':'right', 'duration':30,'targetarea':'full'},
  {'id':31,'woname':'plank','displayname':'plank', 'wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':32,'woname':'plankpushup','displayname':'plankpushup','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':33,'woname':'primalstepup','displayname':'primalstepup','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':34,'woname':'prisoners','displayname':'prisoners','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':35,'woname':'pushuprotate','displayname':'pushuprotate','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':36,'woname':'pushupspider','displayname':'pushupspider','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':37,'woname':'pushups','displayname':'pushups','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':0,'woname':'rest','displayname':'rest','wodirection':'right', 'duration':10,'targetarea':'rest'},
  {'id':38,'woname':'reverselungerotate','displayname':'reverselungerotate','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':39,'woname':'reverselunges','displayname':'reverselunges','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':40,'woname':'shadowboxing','displayname':'shadowboxing','wodirection':'right', 'duration':30,'targetarea':'full'},
  {'id':41.1,'woname':'sideplank','displayname':'sideplank-right','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':41.2,'woname':'sideplank','displayname':'sideplank-left','wodirection':'left', 'duration':30,'targetarea':'core'},
  {'id':42,'woname':'skater','displayname':'skater','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':43,'woname':'sprints','displayname':'sprints','wodirection':'right', 'duration':30,'targetarea':'full'},
  {'id':44,'woname':'squats','displayname':'squats','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':45,'woname':'stepupsquats','displayname':'stepupsquats','wodirection':'right', 'duration':30,'targetarea':'lower'},
  {'id':46,'woname':'surfers','displayname':'surfers','wodirection':'right', 'duration':30,'targetarea':'full'},
  {'id':47,'woname':'swimmers','displayname':'swimmers','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':48,'woname':'toetouches','displayname':'toetouches','wodirection':'right', 'duration':30,'targetarea':'core'},
  {'id':49,'woname':'tricepsdipandreach','displayname':'tricepsdipandreach','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':50,'woname':'tricepsdips','displayname':'tricepsdips','wodirection':'right', 'duration':30,'targetarea':'upper'},
  {'id':51,'woname':'wormwalkouts','displayname':'wormwalkouts','wodirection':'right', 'duration':30,'targetarea':'full'},
];
